name: Feature branch CI
on:
  workflow_dispatch:
  push:
    branches: ['feature/**']
jobs:
  build:
    if: contains(github.ref_name, 'feature')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        id: buildAndTest
        run: ./gradlew clean build

      - name: Archive test report
        if: ${{ success() || (failure() && steps.buildAndTest.conclusion == 'failure') }}
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test

      - name: Analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.branch.name=${{ github.ref_name }} --info
